import { PrismaClient, UniversityType } from '@prisma/client';

const prisma = new PrismaClient();

const universities = [
  // Top Tier US Universities
  {
    name: 'Massachusetts Institute of Technology',
    shortName: 'MIT',
    description:
      'A private land-grant research university in Cambridge, Massachusetts, known for its strong engineering and technology programs.',
    website: 'https://www.mit.edu',
    email: 'admissions@mit.edu',
    phone: '+1-617-253-1000',
    address: '77 Massachusetts Avenue',
    city: 'Cambridge',
    state: 'Massachusetts',
    country: 'United States',
    zipCode: '02139',
    type: UniversityType.PRIVATE,
    establishedYear: 1861,
    studentCount: 11934,
    facultyCount: 3065,
    worldRanking: 1,
    nationalRanking: 2,
    isTopTier: true,
    departments: [
      'Computer Science',
      'Electrical Engineering',
      'Mechanical Engineering',
      'Chemical Engineering',
      'Physics',
      'Mathematics',
      'Economics',
      'Management',
      'Architecture',
      'Biology',
    ],
    popularMajors: [
      'Computer Science',
      'Electrical Engineering and Computer Science',
      'Mechanical Engineering',
      'Mathematics',
      'Physics',
    ],
    graduationRate: 96.0,
    employmentRate: 94.0,
    isPartnershipReady: true,
    partnershipEmail: 'industry-partnerships@mit.edu',
    partnershipContact: 'MIT Industry Liaison Program',
    isActive: true,
    isVerified: true,
  },
  {
    name: 'Stanford University',
    shortName: 'Stanford',
    description:
      'A private research university in Stanford, California, known for its academic strength, proximity to Silicon Valley, and wealth.',
    website: 'https://www.stanford.edu',
    email: 'admission@stanford.edu',
    phone: '+1-650-723-2300',
    address: '450 Jane Stanford Way',
    city: 'Stanford',
    state: 'California',
    country: 'United States',
    zipCode: '94305',
    type: UniversityType.PRIVATE,
    establishedYear: 1885,
    studentCount: 17249,
    facultyCount: 2288,
    worldRanking: 2,
    nationalRanking: 1,
    isTopTier: true,
    departments: [
      'Computer Science',
      'Engineering',
      'Business',
      'Medicine',
      'Law',
      'Education',
      'Humanities and Sciences',
      'Earth Sciences',
    ],
    popularMajors: [
      'Computer Science',
      'Engineering',
      'Economics',
      'Biology',
      'Political Science',
    ],
    graduationRate: 95.0,
    employmentRate: 93.0,
    isPartnershipReady: true,
    partnershipEmail: 'corporate-partnerships@stanford.edu',
    partnershipContact: 'Stanford Corporate Affiliates Program',
    isActive: true,
    isVerified: true,
  },
  {
    name: 'University of California, Berkeley',
    shortName: 'UC Berkeley',
    description:
      'A public land-grant research university in Berkeley, California, known for its academic excellence and research.',
    website: 'https://www.berkeley.edu',
    email: 'admissions@berkeley.edu',
    phone: '+1-510-642-6000',
    address: '200 California Hall',
    city: 'Berkeley',
    state: 'California',
    country: 'United States',
    zipCode: '94720',
    type: UniversityType.PUBLIC,
    establishedYear: 1868,
    studentCount: 45057,
    facultyCount: 3144,
    worldRanking: 4,
    nationalRanking: 3,
    isTopTier: true,
    departments: [
      'Engineering',
      'Computer Science',
      'Business',
      'Letters and Science',
      'Chemistry',
      'Natural Resources',
      'Public Policy',
      'Law',
      'Graduate School of Education',
    ],
    popularMajors: [
      'Computer Science',
      'Electrical Engineering',
      'Economics',
      'Business Administration',
      'Political Science',
    ],
    graduationRate: 92.0,
    employmentRate: 89.0,
    isPartnershipReady: true,
    partnershipEmail: 'industry-relations@berkeley.edu',
    partnershipContact: 'UC Berkeley Industry Relations',
    isActive: true,
    isVerified: true,
  },
  {
    name: 'Carnegie Mellon University',
    shortName: 'CMU',
    description:
      'A private research university in Pittsburgh, Pennsylvania, known for its programs in computer science, engineering, and business.',
    website: 'https://www.cmu.edu',
    email: 'admission@cmu.edu',
    phone: '+1-412-268-2000',
    address: '5000 Forbes Avenue',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    country: 'United States',
    zipCode: '15213',
    type: UniversityType.PRIVATE,
    establishedYear: 1900,
    studentCount: 14799,
    facultyCount: 1482,
    worldRanking: 28,
    nationalRanking: 25,
    isTopTier: true,
    departments: [
      'School of Computer Science',
      'Carnegie Institute of Technology',
      'Tepper School of Business',
      'College of Engineering',
      'College of Fine Arts',
      'Dietrich College of Humanities and Social Sciences',
      'Mellon College of Science',
    ],
    popularMajors: [
      'Computer Science',
      'Engineering',
      'Business Administration',
      'Information Systems',
      'Electrical and Computer Engineering',
    ],
    graduationRate: 89.0,
    employmentRate: 91.0,
    isPartnershipReady: true,
    partnershipEmail: 'corporate-relations@cmu.edu',
    partnershipContact: 'CMU Corporate Relations',
    isActive: true,
    isVerified: true,
  },
  {
    name: 'Georgia Institute of Technology',
    shortName: 'Georgia Tech',
    description:
      'A public research university and institute of technology in Atlanta, Georgia, known for its engineering and technology programs.',
    website: 'https://www.gatech.edu',
    email: 'admission@gatech.edu',
    phone: '+1-404-894-2000',
    address: '225 North Avenue NW',
    city: 'Atlanta',
    state: 'Georgia',
    country: 'United States',
    zipCode: '30332',
    type: UniversityType.PUBLIC,
    establishedYear: 1885,
    studentCount: 36848,
    facultyCount: 1216,
    worldRanking: 38,
    nationalRanking: 35,
    isTopTier: true,
    departments: [
      'College of Engineering',
      'College of Computing',
      'College of Sciences',
      'Scheller College of Business',
      'College of Design',
      'Ivan Allen College of Liberal Arts',
    ],
    popularMajors: [
      'Computer Science',
      'Mechanical Engineering',
      'Industrial Engineering',
      'Electrical Engineering',
      'Business Administration',
    ],
    graduationRate: 87.0,
    employmentRate: 88.0,
    isPartnershipReady: true,
    partnershipEmail: 'industry-partnerships@gatech.edu',
    partnershipContact: 'Georgia Tech Industry Partnerships',
    isActive: true,
    isVerified: true,
  },
  // Add some community colleges and other types
  {
    name: 'Austin Community College',
    shortName: 'ACC',
    description:
      'A public community college district in Austin, Texas, serving the greater Austin area with career and technical education.',
    website: 'https://www.austincc.edu',
    email: 'info@austincc.edu',
    phone: '+1-512-223-7000',
    address: '5930 Middle Fiskville Rd',
    city: 'Austin',
    state: 'Texas',
    country: 'United States',
    zipCode: '78752',
    type: UniversityType.COMMUNITY_COLLEGE,
    establishedYear: 1972,
    studentCount: 43000,
    facultyCount: 2100,
    departments: [
      'Information Technology',
      'Business',
      'Health Sciences',
      'Engineering Technology',
      'Culinary Arts',
      'Automotive Technology',
      'Liberal Arts',
    ],
    popularMajors: [
      'Business Administration',
      'Information Technology',
      'Nursing',
      'Liberal Arts',
      'Engineering Technology',
    ],
    graduationRate: 65.0,
    employmentRate: 78.0,
    isPartnershipReady: true,
    partnershipEmail: 'workforce@austincc.edu',
    partnershipContact: 'ACC Workforce Development',
    isActive: true,
    isVerified: true,
  },
  // International Universities
  {
    name: 'University of Toronto',
    shortName: 'U of T',
    description:
      'A public research university in Toronto, Ontario, Canada, consistently ranked among the top universities globally.',
    website: 'https://www.utoronto.ca',
    email: 'admissions@utoronto.ca',
    phone: '+1-416-978-2011',
    address: "27 King's College Circle",
    city: 'Toronto',
    state: 'Ontario',
    country: 'Canada',
    zipCode: 'M5S 1A1',
    type: UniversityType.PUBLIC,
    establishedYear: 1827,
    studentCount: 97000,
    facultyCount: 2547,
    worldRanking: 18,
    departments: [
      'Engineering',
      'Computer Science',
      'Medicine',
      'Business',
      'Arts and Science',
      'Applied Science and Engineering',
    ],
    popularMajors: [
      'Computer Science',
      'Engineering',
      'Business',
      'Life Sciences',
      'Economics',
    ],
    graduationRate: 85.0,
    employmentRate: 84.0,
    isPartnershipReady: true,
    partnershipEmail: 'partnerships@utoronto.ca',
    partnershipContact: 'University of Toronto Partnerships',
    isActive: true,
    isVerified: true,
  },
  {
    name: 'University of Waterloo',
    shortName: 'Waterloo',
    description:
      'A public research university in Waterloo, Ontario, Canada, known for its co-operative education programs and strong engineering and computer science programs.',
    website: 'https://uwaterloo.ca',
    email: 'admissions@uwaterloo.ca',
    phone: '+1-519-888-4567',
    address: '200 University Avenue West',
    city: 'Waterloo',
    state: 'Ontario',
    country: 'Canada',
    zipCode: 'N2L 3G1',
    type: UniversityType.PUBLIC,
    establishedYear: 1957,
    studentCount: 42000,
    facultyCount: 1300,
    worldRanking: 166,
    departments: [
      'Engineering',
      'Mathematics',
      'Computer Science',
      'Applied Health Sciences',
      'Arts',
      'Environment',
      'Science',
    ],
    popularMajors: [
      'Computer Science',
      'Software Engineering',
      'Electrical Engineering',
      'Mathematics',
      'Mechanical Engineering',
    ],
    graduationRate: 88.0,
    employmentRate: 92.0,
    isPartnershipReady: true,
    partnershipEmail: 'coop@uwaterloo.ca',
    partnershipContact: 'Waterloo Co-operative Education',
    isActive: true,
    isVerified: true,
  },
];

export async function seedUniversities() {
  console.log('🏫 Seeding universities...');

  try {
    // Clear existing universities
    // await prisma.university.deleteMany({});

    // Create universities
    for (const university of universities) {
      // await prisma.university.create({
      //   data: university,
      // });
      await prisma.university.upsert({
        where: {
          name: university.name,
        },
        update: {
          ...university,
          isActive: true,
          isVerified: true,
        },
        create: university,
      });
      console.log(`✅ Created university: ${university.name}`);
    }

    console.log(`🎉 Successfully seeded ${universities.length} universities`);
  } catch (error) {
    console.error('❌ Error seeding universities:', error);
    throw error;
  }
}
